@extends('layout/view-layout')

@section('view-content')
    @include('partial/section/home-banner', [
            'title' => 'Your Main Title Here',
            'subtitle' => 'A brief and compelling description of your product or service.',
            'primaryButtonText' => 'Learn More',
            'primaryButtonUrl' => '/learn-more',
            'secondaryButtonText' => 'Get Started',
            'secondaryButtonUrl' => '/get-started',
            'imageUrl' => '{{ dirname(__DIR__) . /resources/image/home/laptop.png }}',
            'imageAlt' => 'Description of the banner image'
        ])
    @partial('cardsSection')
    @partial('doubleColumnSection')
@endsection

@once
    @push('styles')
        @css('view/home')
    @endpush
@endonce