{{-- Links Block Content --}}
<h6 class="text-uppercase fw-bold mb-4">Links</h6>
<ul class="list-unstyled footer-links">
    <li class="mb-2"><a href="/templates" class="nav-link-footer">Templates</a></li>
    <li class="mb-2"><a href="/components" class="nav-link-footer">Components</a></li>
    <li class="mb-2"><a href="/assets" class="nav-link-footer">Assets</a></li>
    <li class="mb-2"><a href="/documentation" class="nav-link-footer">Documentation</a></li>
</ul>